### ISSUE TITLE
Login with another account from the same "seed"

### ISSUE THREAD

**Issue by dabuchera** [pradel/stacks-ceramic-demo#6]
Hi Léo

Running into the following error when logging in with a second account from the same "seed." Using another Seed is working perfectly.
Not sure if the problem is on my side but it does not look like it. Did you test that?
I will browse through your [pkh-stacks](https://github.com/ceramicnetwork/js-did/tree/1837715e2e9212db76e3ed75e960191fd501c417/packages/pkh-stacks) commit.  Maybe I find something, and if not it is on my side.

![image](https://user-images.githubusercontent.com/53481997/229820739-795bd75f-3af9-4b5c-a0b2-80eeaa7fa3b0.png)

Best

**Comment by pradel** [comment]
It should work, just make sure that you are signing with the same account. Open the Hiro extension and verify that you have selected the account you want to sign with there. If you have selected account 2 in the Hiro extension but are connecting with account 3 on your app you will be signing with account 2 so that might explain the issue

**Comment by pradel** [comment]
In the signing modal you can see the address which is signing the message (can be different to the one you are connected in the app)

**Comment by dabuchera** [comment]
What laziness on my part not to switch in Hiro.
